// <auto-generated />
namespace Buoi3_2011060858_VoDuyPhuoc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BangCatrgoriesandCouses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BangCatrgoriesandCouses));
        
        string IMigrationMetadata.Id
        {
            get { return "202303060712480_Bang Catrgories and Couses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
